<a href="https://colab.research.google.com/github/evelyn2727/proyectos/blob/master/Copia_de_Colab_2_Introducci%C3%B3n_a_TensorFlow_2_0_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow 1.X

### Instalar TensorFlow 1.X



In [1]:
!pip install tensorflow-gpu==1.13.1

     |████████████████████████████████| 345.2MB 40kB/s 
     |████████████████████████████████| 51kB 5.2MB/s 
     |████████████████████████████████| 368kB 20.3MB/s 
     |████████████████████████████████| 3.2MB 28.8MB/s 
ERROR: tensorflow 2.3.0 has requirement tensorboard<3,>=2.3.0, but you'll have tensorboard 1.13.1 which is incompatible.
ERROR: tensorflow 2.3.0 has requirement tensorflow-estimator<2.4.0,>=2.3.0, but you'll have tensorflow-estimator 1.13.0 which is incompatible.
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0


In [2]:
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

ImportError: ignored

In [ ]:
tf.__version__

'1.13.1'

### Constantes

#### Definir una constante

In [ ]:
# Definir una constante en TensorFlow
tensor = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [ ]:
# Si la session no ha sido inicializada, no se pueden acceder a los valores de la constante
tensor.eval()

ValueError: ignored

#### Consultar los valores de la constante

In [ ]:
session = tf.Session()

In [ ]:
session.run(tf.global_variables_initializer())

In [ ]:
tensor_value = session.run(tensor)

In [ ]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variables

#### Definir una variable

In [ ]:
# Definir una variable de TensorFlow 
variable = tf.Variable([[30, 20], [10, 45]])

Instructions for updating:
Colocations handled automatically by placer.


In [ ]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [ ]:
# Si la session no ha sido inicializada, no se podrán acceder a los valores de la variable
variable.eval()

NameError: ignored

#### Consultar los valores de una variable

In [ ]:
# Inicializar una session
session = tf.Session()

In [ ]:
# Inicializar TODAS las variables de la session
session.run(tf.global_variables_initializer())

In [ ]:
# Ejecutar el método eval en el entorno con la sesión iniciada para recuperar los valores del mismo
variable.eval(session)

NameError: ignored

## TensorFlow 2.0

### Instalar TensorFlow 2.0

In [ ]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 55kB/s 
     |████████████████████████████████| 419kB 40.5MB/s 
     |████████████████████████████████| 3.0MB 28.7MB/s 
  Found existing installation: tensorflow-gpu 1.13.1
    Uninstalling tensorflow-gpu-1.13.1:
      Successfully uninstalled tensorflow-gpu-1.13.1


In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.__version__

'2.0.0-alpha0'

### Constantes

#### Definir una constante

In [ ]:
# Definir una constante en TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [ ]:
# Obtener el tamaño de un tensor
tensor_20.shape

TensorShape([2, 2])

#### Consultar los valores de una constante

In [ ]:
# Obtener los valores directamente desde una constante de TensorFlow con numpy, sin necesidad de una session
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [ ]:
# Podemos convertir un array de numpy a un tensor de TensorFlow directamente
numpy_tensor = np.array([[23,  4], [32, 51]])

In [ ]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [ ]:
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variables

#### Definir una variable

In [ ]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Consultar los valores de una variable

In [ ]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Cambiar un valor especifico de una variable

In [ ]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [ ]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operaciones con tensores

In [ ]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=27, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Sumar un escalar a un tensor

In [ ]:
tensor + 2

<tf.Tensor: id=30, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicar un escalar por un tensor

In [ ]:
tensor * 5

<tf.Tensor: id=33, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Utilizar funciones de Numpy sobre tensores de TensorFlow

In [ ]:
# Obtener los cuadrados de todos los números de un tensor de TensorFlow
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [ ]:
# Obtener la raíz cuadrada de todos los números de un tensor de TensorFlow
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Producto escalar entre dos tensores

In [ ]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings en TensorFlow 2.0

In [ ]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=41, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operaciones simples con strings

In [ ]:
tf.strings.length(tf_string)

<tf.Tensor: id=43, shape=(), dtype=int32, numpy=10>

In [ ]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=48, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Almacenar arrays de strings

In [ ]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [ ]:
# Iterar sobre un array de strings en TF
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
